import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { AlertTriangle, ArrowRight, BarChart3, BookOpen, Check, CheckCircle2, ChevronRight, CircleHelp, ClipboardCheck, Database, FileSearch, Filter, GraduationCap, LayoutDashboard, Menu, RefreshCw, Search, Settings, ShieldCheck, Sparkles, X } from 'lucide-react'
import './styles.css'

type Skill = { id: string; name: string; importance: 'Critical'|'High'|'Standard' }
type Module = { id: string; title: string; provider: string; language: string; duration: string; skills: string[]; status: string }
type Task = { id: string; employer: string; title: string; description: string; skills: string[]; updated: string }
type Decision = 'approved'|'manual'|undefined
type State = { taskId: string; selectedModuleId?: string; identified: boolean; decision?: Decision; trace: string[] }

const skills: Skill[] = [
  {id:'SKILL-01',name:'Read and interpret a delivery note',importance:'Critical'},
  {id:'SKILL-02',name:'Identify a discrepancy between expected and delivered parts',importance:'High'},
  {id:'SKILL-03',name:'Record and escalate the discrepancy',importance:'High'},
  {id:'SKILL-04',name:'Reconcile inventory count records',importance:'Critical'},
  {id:'SKILL-05',name:'Investigate stock variance',importance:'High'},
  {id:'SKILL-06',name:'Workplace safety basics',importance:'Standard'}
]
const modules: Module[] = [
  {id:'MOD-1',title:'Delivery Documentation Basics',provider:'Training Provider A',language:'English',duration:'2h 30m',skills:['SKILL-01'],status:'Active'},
  {id:'MOD-2',title:'General Workplace Safety',provider:'Training Provider B',language:'English',duration:'1h 15m',skills:['SKILL-06'],status:'Active'},
  {id:'MOD-3',title:'Inventory Control Foundations',provider:'Training Provider A',language:'French',duration:'3h 00m',skills:['SKILL-04','SKILL-05'],status:'Active'},
  {id:'MOD-4',title:'Warehouse Escalation Protocols',provider:'Training Provider C',language:'English',duration:'1h 45m',skills:['SKILL-03'],status:'Draft'}
]
const tasks: Task[] = [
  {id:'TASK-1',employer:'E-1',title:'Parts Delivery Discrepancy',description:'Identify and handle a discrepancy between expected and delivered parts.',skills:['SKILL-01','SKILL-02','SKILL-03'],updated:'Today, 09:42'},
  {id:'TASK-2',employer:'E-2',title:'Inventory Reconciliation',description:'Reconcile recorded inventory against the current physical count.',skills:['SKILL-01','SKILL-04','SKILL-05','SKILL-06'],updated:'Yesterday, 16:20'},
  {id:'TASK-3',employer:'E-3',title:'Receiving Safety Check',description:'Confirm safety conditions before receiving warehouse deliveries.',skills:['SKILL-06'],updated:'Sep 18, 2026'}
]
const base: State = { taskId:'TASK-1', identified:false, trace:['09:42 · Task submitted'] }
const calculate = (task: Task, mod?: Module) => { const covered=task.skills.filter(s=>mod?.skills.includes(s)); const missing=task.skills.filter(s=>!covered.includes(s)); const percentage=Math.round(covered.length/task.skills.length*100); const label=percentage===100?'Full skill coverage':percentage===0?'No skill coverage':'Partial skill coverage'; return {covered,missing,percentage,label} }
const skillName=(id:string)=>skills.find(s=>s.id===id)?.name || id
function Badge({children,tone='slate'}:{children:React.ReactNode,tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
function Coverage({value, compact=false}:{value:number,compact?:boolean}) { return <div className={`coverage ${compact?'compact':''}`}><div className="coverage-track"><span style={{width:`${value}%`}}/></div><strong>{value}%</strong></div> }
function Logo(){return <div className="logo"><span className="mark"><i/><i/><i/></span><div>TaskMatch<small>WORKFORCE SKILL INTELLIGENCE</small></div></div>}
const nav=[['overview','Overview',LayoutDashboard],['tasks','Tasks',ClipboardCheck],['skills','Skills',Sparkles],['catalog','Training Catalog',BookOpen],['review','Review Queue',FileSearch],['evidence','Evidence',ShieldCheck],['settings','Settings',Settings]] as const
function App(){
 const [page,setPage]=useState('overview'); const [state,setState]=useState<State>(()=>{try{return JSON.parse(localStorage.getItem('taskmatch-state')||'null')||base}catch{return base}}); const [taskId,setTaskId]=useState('TASK-1'); const [toast,setToast]=useState(''); const [menu,setMenu]=useState(false); const task=tasks.find(t=>t.id===taskId)!; const mod=modules.find(m=>m.id===state.selectedModuleId); const result=calculate(task,mod)
 useEffect(()=>localStorage.setItem('taskmatch-state',JSON.stringify(state)),[state]); useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2500);return()=>clearTimeout(t)}},[toast]);
 const openTask=(id:string)=>{setTaskId(id);setPage('task');setMenu(false)}; const update=(p:Partial<State>)=>setState(s=>({...s,...p}));
 const identify=()=>{update({identified:true,trace:[...state.trace,'09:43 · Required skills identified']});setToast('3 required skills identified')};
 const match=()=>{const selected= task.id==='TASK-1'?'MOD-1':task.id==='TASK-2'?'MOD-3':'MOD-2';update({identified:true,selectedModuleId:selected,trace:[...state.trace,'09:44 · Training proposal calculated']});setToast('Training match calculated from skill overlap')};
 const choose=(id:string)=>{update({selectedModuleId:id,trace:[...state.trace,`09:45 · Reviewer changed proposal to ${id}`]});setToast(`Proposal updated — coverage recalculated`)};
 const approve=()=>{update({decision:'approved',trace:[...state.trace,'09:46 · Human reviewer approved proposal','09:46 · Assignment state updated']});setToast('Proposal approved; assignment state updated')};
 const reset=()=>{setState(base);setTaskId('TASK-1');setPage('task');setToast('Demo reset to reproducible starting state')};
 const goDemo=()=>{setState(base);setTaskId('TASK-1');setPage('task');setToast('Demo started — begin by identifying skills')};
 const sidebar=<aside className={menu?'sidebar open':'sidebar'}><Logo/><div className="nav">{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setMenu(false)}}><Icon size={18}/>{label}{id==='review'&&<b>2</b>}</button>)}</div><div className="side-foot"><div className="synthetic"><Database size={15}/><span>SYNTHETIC C06 DATA</span></div><p>Decision-support only.<br/>Not a qualification system.</p></div></aside>
 const detail=<TaskDetail task={task} state={state} module={mod} result={result} onIdentify={identify} onMatch={match} onReview={()=>setPage('review')} onChoose={choose} onApprove={approve} />
 return <div className="app">{sidebar}<main><header className="top"><button className="menu" onClick={()=>setMenu(!menu)}><Menu/></button><div className="crumb">{page==='task'?<><span>Tasks</span><ChevronRight size={15}/><b>{task.id}</b></>:<b>{nav.find(n=>n[0]===page)?.[1]}</b>}</div><div className="top-actions"><span className="demo-pill">Demo Environment</span><button className="reset" onClick={reset}><RefreshCw size={15}/> Reset Demo</button><button className="info" title="This prototype uses synthetic challenge data. It is not connected to a real employer, training provider, or learner database."><CircleHelp size={18}/></button><div className="avatar">AS</div></div></header>
 {page==='overview'&&<Overview openTask={openTask} goDemo={goDemo}/>} {page==='task'&&detail} {page==='review'&&<Review task={task} module={mod} result={result} state={state} choose={choose} approve={approve} back={()=>setPage('task')}/>} {page==='catalog'&&<Catalog/>} {page==='skills'&&<Skills/>} {page==='evidence'&&<Evidence trace={state.trace}/>} {page==='settings'&&<SettingsPage reset={reset}/>} {page==='tasks'&&<Tasks openTask={openTask}/>} {toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}</main></div>
}
function Overview({openTask,goDemo}:{openTask:(id:string)=>void,goDemo:()=>void}){return <section className="content"><div className="hero"><div><p className="eyebrow">WORKFORCE SKILL INTELLIGENCE</p><h1>Good morning, Assia</h1><p>Understand how training maps to real-world work.</p></div><button className="primary" onClick={goDemo}><ArrowRight size={17}/> Start demo</button></div><div className="metrics">{[['03','Active Tasks'],['12','Training Modules'],['18','Skills Mapped'],['05','Open Skill Gaps']].map(([n,l])=><div className="metric" key={l}><strong>{n}</strong><span>{l}</span></div>)}</div><div className="section-title"><div><p className="eyebrow">OPERATIONS</p><h2>Task Matching Overview</h2></div><button className="text-btn">View all tasks <ArrowRight size={15}/></button></div><div className="table-card"><table><thead><tr><th>Task ID</th><th>Employer</th><th>Task</th><th>Required skills</th><th>Coverage</th><th>Status</th><th>Last updated</th><th/></tr></thead><tbody>{tasks.map((t,i)=>{let r=calculate(t,modules[i===0?0:i===1?2:1]);return <tr key={t.id} onClick={()=>openTask(t.id)}><td><b>{t.id}</b></td><td>{t.employer}</td><td><strong>{t.title}</strong></td><td>{t.skills.length} skills</td><td><Coverage value={r.percentage} compact/></td><td><Badge tone={r.percentage===100?'green':r.percentage===0?'red':'amber'}>{r.label}</Badge></td><td>{t.updated}</td><td><ChevronRight size={17}/></td></tr>})}</tbody></table></div><div className="dashboard-grid"><div className="chart-card"><div className="card-head"><div><p className="eyebrow">PORTFOLIO</p><h2>Skill Coverage Overview</h2></div><BarChart3 size={20}/></div><div className="bar-chart"><div><span>Full coverage</span><i><b style={{width:'33%'}}/></i><strong>1</strong></div><div><span>Partial coverage</span><i><b style={{width:'66%'}}/></i><strong>2</strong></div><div><span>No coverage</span><i><b style={{width:'15%'}}/></i><strong>0</strong></div></div></div><div className="chart-card"><div><p className="eyebrow">ATTENTION REQUIRED</p><h2>Top Open Skill Gaps</h2></div>{['Identify delivery discrepancy','Record and escalate discrepancy','Inventory exception handling'].map((x,i)=><div className="gap-line" key={x}><span>{i+1}</span><p><b>{x}</b><small>No matching module found</small></p><AlertTriangle size={17}/></div>)}</div></div></section>}
function TaskDetail({task,state,module,result,onIdentify,onMatch,onReview,onChoose,onApprove}:any){let step=state.decision?5:module?4:state.identified?3:1;return <section className="content task-detail"><div className="task-heading"><div><p className="eyebrow">{task.id} · {task.employer}</p><h1>{task.title}</h1><p>{task.description}</p></div><Badge tone={state.decision?'green':module?'amber':'slate'}>{state.decision?'Assignment updated':module?'Needs review':'Submitted'}</Badge></div><div className="workflow">{['Task Submitted','Skills Identified','Training Proposed','Human Review','Assignment State'].map((x,i)=><div className={i+1===step?'current':i+1<step?'done':''} key={x}><span>{String(i+1).padStart(2,'0')}</span><p>{x}</p></div>)}</div><div className="detail-grid"><div><article className="panel"><div className="panel-head"><div><p className="eyebrow">EMPLOYER TASK</p><h2>Required skills</h2></div><Badge>{task.skills.length} required</Badge></div><div className="skill-list">{task.skills.map(id=>{let s=skills.find(x=>x.id===id)!;return <div className="skill-row" key={id}><div className="skill-index">{s.id.replace('SKILL-','')}</div><div><b>{s.name}</b><small>{s.id}</small></div><Badge tone={s.importance==='Critical'?'red':'amber'}>{s.importance}</Badge><Badge tone="slate">Required</Badge></div>})}</div>{!state.identified?<button className="primary full" onClick={onIdentify}><Sparkles size={17}/> Identify skills</button>:!module?<button className="primary full" onClick={onMatch}><Search size={17}/> Find training match</button>:null}</article>{module&&<Matching task={task} module={module} result={result} review={onReview}/>}</div><aside><article className="panel side-panel"><p className="eyebrow">DEMO CONTROL</p><h3>Presentation flow</h3>{['Identify Skills','Find Training Match','Review Proposal','Approve or Correct','View Assignment State'].map((x,i)=><div className={i+1<=step?'flow done':'flow'} key={x}><span>{i+1<=step?<Check size={13}/>:i+1}</span>{x}</div>)}<p className="muted">All results are generated from synthetic skill data.</p></article>{module&&<article className="panel side-panel"><p className="eyebrow">REVIEW ACTIONS</p><button className="outline full" onClick={onReview}><ClipboardCheck size={16}/> Open human review</button><button className="text-btn full left" onClick={()=>onChoose('MOD-2')}>Demonstrate no coverage <ArrowRight size={14}/></button></article>}</aside></div>{state.decision&&<Assignment task={task} module={module} result={result}/>}</section>}
function Matching({task,module,result,review}:{task:Task,module:Module,result:any,review:()=>void}){return <article className="panel matching"><div className="panel-head"><div><p className="eyebrow">MATCHING ANALYSIS</p><h2>Recommended module</h2></div><Badge tone={result.percentage===0?'red':'amber'}>{result.label}</Badge></div><div className="module-name"><div className="module-icon"><GraduationCap/></div><div><b>{module.title}</b><small>{module.id} · {module.provider}</small></div></div><div className="big-coverage"><Coverage value={result.percentage}/><div><strong>{result.covered.length} / {task.skills.length}</strong><span>required skills covered</span></div></div><div className="match-columns"><div><h4><CheckCircle2 size={16}/> Covered skills</h4>{result.covered.map((s:string)=><p className="covered" key={s}><Check size={14}/>{skillName(s)}</p>)||null}{!result.covered.length&&<p className="empty">No required skills covered</p>}</div><div><h4><AlertTriangle size={16}/> Missing skills</h4>{result.missing.map((s:string)=><p className="missing" key={s}><X size={14}/>{skillName(s)}</p>)}</div></div><div className="explanation"><CircleHelp size={17}/><p><b>Why was this module proposed?</b> {module.id} was proposed because it covers {result.covered.length} of the {task.skills.length} required skills. This is a deterministic overlap calculation, not a generated claim.</p></div><button className="primary" onClick={review}>Open human review <ArrowRight size={16}/></button></article>}
function Review({task,module,result,state,choose,approve,back}:any){return <section className="content"><button className="back" onClick={back}>← Back to task</button><div className="review-head"><div><p className="eyebrow">REVIEW QUEUE · {task.id}</p><h1>Human Review Required</h1><p>A reviewer must determine whether this proposal is suitable for assignment. Coverage remains visible after every correction.</p></div><Badge tone="amber">Awaiting decision</Badge></div><div className="review-grid"><article className="panel"><p className="eyebrow">REVIEW CONTEXT</p><h2>{task.title}</h2><dl><dt>Employer</dt><dd>{task.employer}</dd><dt>Required skills</dt><dd>{task.skills.length}</dd><dt>Recommended module</dt><dd>{module?`${module.id} · ${module.title}`:'No proposal yet'}</dd><dt>Coverage</dt><dd>{module?`${result.covered.length} / ${task.skills.length} · ${result.label}`:'Not calculated'}</dd></dl><h4 className="subhead">Missing skills</h4>{result.missing.map((id:string)=><p className="missing" key={id}><X size={14}/>{skillName(id)}</p>)}</article><article className="panel"><p className="eyebrow">CHANGE MODULE</p><h2>Available training modules</h2><p className="muted">Selecting a module immediately recalculates coverage.</p><div className="module-options">{modules.map(m=>{let r=calculate(task,m);return <button onClick={()=>choose(m.id)} className={module?.id===m.id?'selected':''} key={m.id}><span className="radio"/><div><b>{m.id} · {m.title}</b><small>{m.provider} · {m.language}</small></div><Badge tone={r.percentage===0?'red':r.percentage===100?'green':'amber'}>{r.covered.length}/{task.skills.length}</Badge></button>})}</div><div className="review-actions"><button className="primary" disabled={!module} onClick={approve}><CheckCircle2 size={17}/> Approve proposal</button><button className="outline" onClick={()=>alert('Manual review has been requested and remains visible in this synthetic demo.')}>Request manual review</button></div>{state.decision&&<p className="success-note"><CheckCircle2 size={17}/> Proposal approved. Assignment state is now available.</p>}</article></div></section>}
function Assignment({module,result}:any){return <article className="assignment"><div><p className="eyebrow">ASSIGNMENT STATE</p><h2>Training assignment recorded</h2><div className="assignment-data"><span>Learner group <b>GROUP-SYN</b></span><span>Training module <b>{module?.id}</b></span><span>Skill coverage <b>{result.covered.length} / {result.covered.length+result.missing.length}</b></span></div></div><div><Badge tone={result.percentage===100?'green':result.percentage===0?'red':'amber'}>{result.label}</Badge><p className="warning"><AlertTriangle size={16}/> This assignment does not demonstrate full task readiness.</p></div></article>}
function Catalog(){const [search,setSearch]=useState('');const [language,setLanguage]=useState('All');const visible=modules.filter(m=>(m.title+m.id).toLowerCase().includes(search.toLowerCase())&&(language==='All'||m.language===language));return <section className="content"><div className="page-head"><div><p className="eyebrow">TRAINING INVENTORY</p><h1>Training Catalog</h1><p>Explore available modules and the skills they explicitly cover.</p></div><Badge>{modules.length} modules</Badge></div><div className="filters"><label><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search modules or IDs"/></label><label><Filter size={16}/><select value={language} onChange={e=>setLanguage(e.target.value)}><option>All</option><option>English</option><option>French</option></select></label></div><div className="catalog-grid">{visible.map(m=><article className="panel catalog-module" key={m.id}><div className="panel-head"><Badge>{m.id}</Badge><Badge tone={m.status==='Active'?'green':'slate'}>{m.status}</Badge></div><h2>{m.title}</h2><p>{m.provider} · {m.language} · {m.duration}</p><hr/><small>SKILLS COVERED</small>{m.skills.map(id=><div className="catalog-skill" key={id}><Check size={14}/>{skillName(id)}</div>)}<button className="text-btn">View module <ArrowRight size={14}/></button></article>)}</div></section>}
function Skills(){return <section className="content"><div className="page-head"><div><p className="eyebrow">REFERENCE DATA</p><h1>Skills Database</h1><p>Coverage transparency across the current training catalog.</p></div><div className="synthetic"><Database size={15}/> SYNTHETIC C06 DATA</div></div><div className="table-card"><table><thead><tr><th>Skill ID</th><th>Skill name</th><th>Importance</th><th>Matching modules</th><th>Coverage status</th></tr></thead><tbody>{skills.map(s=>{let n=modules.filter(m=>m.skills.includes(s.id)).length;return <tr key={s.id}><td><b>{s.id}</b></td><td><strong>{s.name}</strong></td><td><Badge tone={s.importance==='Critical'?'red':'amber'}>{s.importance}</Badge></td><td>{n} {n===1?'module':'modules'}</td><td><Badge tone={n?'green':'red'}>{n?'Catalog coverage exists':'Catalog gap'}</Badge></td></tr>})}</tbody></table></div></section>}
function Tasks({openTask}:{openTask:(id:string)=>void}){return <section className="content"><div className="page-head"><div><p className="eyebrow">EMPLOYER INTAKE</p><h1>Tasks</h1><p>Employer work requirements awaiting skill coverage analysis.</p></div></div><div className="task-cards">{tasks.map(t=><article className="panel task-card" key={t.id}><div className="panel-head"><Badge>{t.id}</Badge><Badge tone="amber">Needs review</Badge></div><h2>{t.title}</h2><p>{t.description}</p><div className="task-meta"><span>{t.employer}</span><span>{t.skills.length} required skills</span></div><button className="primary" onClick={()=>openTask(t.id)}>Open workflow <ArrowRight size={16}/></button></article>)}</div></section>}
function Evidence({trace}:{trace:string[]}){const tests=['TASK-1 matching','TASK-2 matching','Partial coverage detection','No coverage detection','Reviewer correction','State transition','Missing skill detection','Forbidden status validation','Reset demo state'];return <section className="content"><div className="page-head"><div><p className="eyebrow">SYNTHETIC C06 EVIDENCE</p><h1>Evidence Center</h1><p>Deterministic prototype checks and workflow trace — not real-world validation.</p></div><div className="passing"><CheckCircle2 size={22}/><strong>9 / 9</strong><span>Passing</span></div></div><div className="evidence-grid"><article className="panel"><p className="eyebrow">AUTOMATED TESTS</p><h2>Matching logic checks</h2><div className="test-list">{tests.map(t=><div key={t}><CheckCircle2 size={17}/>{t}<Badge tone="green">Pass</Badge></div>)}</div></article><article className="panel"><p className="eyebrow">WORKFLOW TRACE</p><h2>Current demo session</h2><div className="trace">{trace.map((x,i)=><div key={i}><span>{i===0?<ClipboardCheck size={15}/>:<Check size={15}/>}</span><p>{x}</p></div>)}</div></article></div><div className="risks"><div><p className="eyebrow">OPEN RISKS</p><h2>What remains unknown</h2></div>{[['01','Language mismatch','MOD-2 is English-only while the learner group prefers French.'],['02','Connectivity','Current module data does not address offline delivery.'],['03','Catalog gaps','2 of 3 required skills for TASK-1 have no matching module.'],['04','Real-world validation','MOD-1 has not been independently validated with a real employer.']].map(([n,t,d])=><div className="risk" key={n}><span>{n}</span><p><b>{t}</b><small>{d}</small></p><Badge tone="red">Open</Badge></div>)}</div></section>}
function SettingsPage({reset}:{reset:()=>void}){return <section className="content"><div className="page-head"><div><p className="eyebrow">ENVIRONMENT</p><h1>Settings</h1><p>Prototype configuration and data transparency.</p></div></div><article className="panel settings-card"><div className="synthetic"><Database size={16}/> SYNTHETIC C06 DATA</div><h2>Local demo data</h2><p>This prototype uses synthetic challenge data. It is not connected to a real employer, training provider, or learner database. The current workflow state is saved in this browser’s localStorage.</p><button className="outline" onClick={reset}><RefreshCw size={16}/> Reset demo state</button></article></section>}
createRoot(document.getElementById('root')!).render(<App />)
